Separando os testes para DevOps e S.R.E
ZXVentures/code-challenge pull request #46
Opened 2022-05-10 13:25 UTC by carlosmcdojr

2022-05-10 13:42 UTC, luanhdeandrade requested changes

2022-05-10 13:42 UTC, luanhdeandrade commented on devops-cloud.md
> +Is all about scripting and the goal is to create a tool to retrieve information from AWS S3 buckets.
"It is" ou "This is"

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +This first one is build an simple infrastructure as code (AWS).
Você já falou que é o primeiro, então "This first one" fica redundante. Pode deixar somente "Build a simple infrastructure as code" (Não se usa an antes de palavras com consoante)

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +- Take good care of the Readme, explaining how your solution was designed and how to deploy it
Write an adorably good readme

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +### Advice
General Guidance

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +Points may have a much-needed ability to make technical decisions.
O que você quer dizer aqui exatamente nessa linha 27?

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +If in doubt, do not hesitate to ask us.
Should you have any questions or regards about the test, do not hesitate do ask us

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +This second challenge is more like a case than a code challenge itself.
Também fica redundante falar que este é o segundo. Acho até que dá pra descartar essa frase inteira, já que ela não diz muito para quem quer fazer o teste.

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +Imagine that we are starting Zé Delivery at this moment and we are recruiting the team and finally starting the development of Zé's products, which are:
Acho desnecessário falar que estamos recrutando a equipe. Eu cortaria. Deixaria algo como "Imagine we are starting to build the very first version of Zé Delivery platform, considering:"

2022-05-10 13:42 UTC, luanhdeandrade commented on sre-cloud.md
> +In a fresh AWS cloud account, how would you draw Zé's infrastructure, considering all the services we want to develop? Think about security, network, communication, databases, etc. While drawing, we
Importante frisar que não é só desenhar, mas sim também construir.

2022-05-10 17:48 UTC, carlosmcdojr commented on sre-cloud.md
> +Points may have a much-needed ability to make technical decisions.
Apenas mantive o padrão antigo. Como acha que podemos melhorar?

2022-05-10 19:25 UTC, luanhdeandrade commented on sre-cloud.md
> +Points may have a much-needed ability to make technical decisions.
Sei lá, talvez tirar? Não entendi o que ela quer dizer

2022-05-10 20:25 UTC, luanhdeandrade requested changes

2022-05-10 20:25 UTC, luanhdeandrade commented on sre-cloud.md
> +We have two challenges, the first one is an intermediate test, and the second is a more advanced: The both challenges is about defining an architecture for Zé at AWS, considering several requirements
Linha 5:
Só fui perceber agora esse "The both challenges" (plural) "... is about" (singular). Corrigir concordância verbal.

"[...] considering several requirements that are necessary to consider"
Considerando os requisitos que são necessários de considerar? Ruim essa frase né? Só vi agora também.

2022-05-13 13:11 UTC, chahadze approved these changes

2022-05-13 15:41 UTC, liciomatos approved these changes

2022-05-13 15:42 UTC, liciomatos approved these changes

2022-05-13 15:47 UTC, liciomatos approved these changes
Om

2022-05-13 15:56 UTC, merged